# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do

    FIREBASE_CLI_TOKEN = ENV["FIREBASE_CLI_TOKEN"]
    FIREBASE_APP_ID = ENV["FIREBASE_APP_ID"]

    desc "Runs all the tests"
      lane :runTests do
        gradle(task: "test")
    end

    desc "Get latest build version from Firebase App Distribution"
        lane :getLatestVersionAndUpgrade do
            latest_release = firebase_app_distribution_get_latest_release(
                app: FIREBASE_APP_ID,
                service_credentials_file: "private-decoded-key.json")
            buildNumber = latest_release.nil? ? 1 : latest_release[:buildVersion].to_i
            puts buildNumber
            increment_version_code({ version_code: buildNumber + 1 })
    end

    desc "Upload release apk on firebase app distribution"
        lane :uploadApkToFirebase do
            gradle(task: "assemble", build_type: "debug")
            firebase_app_distribution(
            app: FIREBASE_APP_ID,
            firebase_cli_token: FIREBASE_CLI_TOKEN,
            android_artifact_type: "APK",
            android_artifact_path: "app/build/outputs/apk/debug/app-debug.apk",
            groups: "testers"
            )
    end
end
