name: Create and Upload Build on Firebase App Distribution

on:
  push:
    branches: [ main ]

jobs:
  CI-Upload-APK:
    name: Debug build uploading
    runs-on: ubuntu-latest

    env:
      FIREBASE_CLI_TOKEN: ${{secrets.FIREBASE_TOKEN}}
      FIREBASE_APP_ID: ${{secrets.FIREBASE_APP_ID}}
      CREDENTIAL_FILE_CONTENT: ${{secrets.CREDENTIAL_FILE_CONTENT}}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'

      - name: Install Bundler & Fastlane
        run: |
          gem install bundler:2.6.2
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Install Firebase App Distribution Plugin
        run: bundle exec fastlane add_plugin firebase_app_distribution

      - name: Install Build version increment Plugin
        run: bundle exec fastlane add_plugin increment_version_code

      - name: Generate private-decoded-key.json file
        run: echo "$CREDENTIAL_FILE_CONTENT" | base64 -d > private-decoded-key.json

      - name: Upgrade build version
        run: bundle exec fastlane getLatestVersionAndUpgrade

      - name: Run tests
        run: bundle exec fastlane runTests

      - name: Upload .apk to Firebase
        run: bundle exec fastlane uploadApkToFirebase